#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.0

pull_requests:  
  do_not_increment_build_number: true

nuget:  
  disable_publish_on_pr: true

image:
- Visual Studio 2017

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  CODECOV_TOKEN: 
    secure: p0ajkgqnPFc6xmwGcsMGJFXgz++MceXp1MuzGn42fAqjvIIUKPN3alcnHDdlbwSJ

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - sh build.sh Release

# scripts to run after build
after_build:
  - sh pack.sh

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory .\OpenCover

# to run your custom scripts instead of automatic tests
test_script:
  - sh test.sh

# scripts to run after tests
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f ".\coverage.xml" -X gcov --token=%CODECOV_TOKEN%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: .\artifacts\**\*.nupkg
    name: NuGet

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  - provider: NuGet
    api_key:
      secure: U1K7EOzwg7+VEfxBE/nopyThqc8s/iNkPc9VLITFWUJubeIDuu6O3V0MIuVQDEg9
    skip_symbols: true
    on:
      APPVEYOR_REPO_TAG: true
