name: Main

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      run: bash ./build.sh
      
    - name: Test
      run: bash ./test.sh
